---
title: "Todos pela Popularidade: Como o Apoio do Presidente é Capaz de Afetar o Posicionamento dos Parlamentares Brasileiros." 
author: "Andéliton Soares"
date: "10/12/2020"
output: 
  html_document:
   toc: true
   theme: united
   toc_float: true
   number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introdução 

  Ainda há muito a se explorar acerca das implicações políticas do novo Coronavírus. A pandemia toca em diversas dimensões da análise política: comportamental, políticas públicas, federalismo, liderança, e, também, política legislativa. Para a saúde e gestão públicas, apresenta-se como um dos maiores desafios dos últimos tempos e, longe de limitar-se a gestores e especialistas, apresenta-se como grande problema aos pesquisadores. 
  	
  Ademais, está relacionado a grandes temas sobre a capacidade da democracia de responder à crises (KAVANAGH; SINGH, 2020), as implicações geradas pela delimitação conceitual acerca dos óbitos em pesquisas comparadas (KARANIKOLOS; MONITOR, 2020), e a existência de desafios analíticos apresentados através das diversas estruturas de processo decisório, exposição midiática e organização de sistemas de saúde (BAL et al., 2020). Relata-se a especificidade da condução de políticas de saúde em relação às demais áreas de políticas públicas, sendo até mesmo defendida a tese da necessidade de um campo específico dentro da Ciência Política para o seu debate (MORONE; JACOBS, 2005). Junta-se a isso o fato de ser área extremamente sensível a parâmetros de justiça e igualdade,  produzindo complexo emaranhado de identidades através do trato com doenças e assistência (CARPENTER, 2012). 
	No que diz respeito ao enfoque político, é possível observar uma grande preocupação com dimensões de enfrentamento da crise. Analisa-se o quão capazes de produzir resultados são as ações tomadas, tendo por pano de fundo os diferentes regimes políticos, formas de estado, poderes estatais, e parâmetros de avaliação de políticas públicas (GREER et al., 2020).
 Porém, o enfoque político do fenômeno, como será defendido, não só torna possível maior compreensão das medidas tomadas e de seus efeitos, contribuindo para entendimentos de maior escala, senão que lança luz a uma importante dimensão do problema - a administração de prejuízos. Mais especificamente, como os problemas gerados pela pandemia podem inaugurar um importante cenário de reivindicação de crédito e de esquiva de responsabilidade. O choque existente entre a Presidência da República e governos estaduais já é relatado como embate de responsabilidades (MELO, 2020).
O presente artigo argumenta que a pandemia é um desafio político: é fonte de inevitáveis perdas, fazendo forças políticas não só se organizarem para o seu combate, mas, igualmente, para a administração do prejuízo político gerado.  A literatura demonstra como pandemias anteriores concentram extrema sensibilidade através do caos e da crise gerados. A realidade é desastrosa e repleta de viés negativo, independente dos passos e da agilidade da ação governamental (FLINDERS, 2020). Tomando o enfoque da tendência ao maior impacto de perdas gerado pela maior sensibilidade a prejuízos do que ganhos (WEAVER, 1986), o produto acaba sendo a abertura para “jogos de culpa” que cria diferentes cenários de “esquiva de culpabilidade” (HOOD, 2010).
A pandemia, por outro lado, pode ser vista como choque exógeno, tendo a capacidade de criar oportunidades como fator unificador através do conceito de “Todos pela Pátria”, rally-‘round-the-flag ,  como ocorre no caso dinamarquês e britânico (BAEKGAARD et al., 2020; FLINDERS, 2020). Nesse sentido, teria um efeito moderador nas preferências políticas de elites e massa. Na massa, também, o medo da morte pode gerar incentivos para posturas críticas às soluções miraculosas e não científicas para o problema, projetando a população igualmente para um caminho de moderação (Pereira et. al 2020).
Por outro lado, pode ser também uma ferramenta para o aprofundamento de clivagens e da polarização política, principalmente em países governados por políticos populistas que adotam uma postura negacionista (MEYER, 2020). O Brasil, no caso, é um dos países (cinco no mundo) com uma liderança política que menospreza e reduz os impactos da pandemia, conforme aponta Meyer. Ressalta-se a importante comoção gerada por medidas contrárias ao distanciamento social por parte do Poder Executivo Federal, acompanhada de queda de popularidade nos momentos iniciais da pandemia. Após alguns meses, a popularidade do Presidente da República volta a crescer em um cenário agravante da pandemia do novo Coronavírus ao redor do mundo, existindo flexibilização do distanciamento social em diversas partes do Brasil. Bolsonaro se portou porta-voz da necessidade de flexibilização das restrições impostas à circulação de pessoas, defendendo a necessidade de abrir a economia. Fez questão de contrapor economia e pandemia, alertando para os problemas gerados no tratamento da segunda para a primeira.
Neste artigo, contribuímos com o debate através de uma análise das posições em relação ao enfretamento da pandemia adotadas pelas duas casas do Poder Legislativo brasileiro, matizado pela ideologia dos partidos e sua proximidade com o governo. Colocamos algumas questões que iremos responder com dados dos discursos parlamentares proferidos em ambas as casas. Dessa forma, busca-se saber o posicionamento dos parlamentares com relação às ações e posturas do Governo Federal, e ao distanciamento social.
         Para conduzir o presente trabalho, serão considerados os discursos proferidos pelos parlamentares das duas Casas legislativas brasileiras, de março até o fim de agosto de 2020. Os seus discursos serão avaliados de acordo com as críticas e elogios feitos ao Poder Executivo Federal, tendo por unidade de análise os partidos, contrastados por sua ideologia e participação no governo. Junta-se a isso o interesse em saber como os partidos se comportaram em relação ao distanciamento social, fortemente recomendado por autoridades internacionais e adotado por diversos países, e às ações de gasto público através da transferência de recursos a cidadãos em situação de vulnerabilidade. 
Por fim, observaremos o quanto o Poder Legislativo, se uniu entorno do enfrentamento da pandemia. Iremos investigar se partidos de matizes ideológicas distintas se aliaram em âmbito legislativo na defesa de medidas de enfrentamento à crise gerada pela pandemia da Covid-19. 
 	A validade teórica das correlações empíricas pode apontar para elementos acerca da gestão da crise, sendo o efeito da opinião pública entendido como variável de peso para os pronunciamentos do Parlamento. Assim, poderemos verificar o quão custoso seria defender o Presidente em momentos de queda de seu apoio popular e o quanto a oposição pode aproveitar-se da fragilidade Presidencial ou abster-se do conflito. Analisamos como governo e oposição dividem o peso da responsabilidade e/ou se aproveitam dela. 
	Os resultados demonstram que partidos de esquerda são críticas de forma consistente no tempo às posições do governo, de ataques e críticas a pedidos de abertura de processos de impeachment. Já partidos ao centro e à direita evitam o tema e a criticar o Presidente. Com o crescimento da popularidade presidencial, esses partidos passam a se expor mais em defesa das ações do Governo Federal, demonstrando certo grau de aversão ao risco em momentos de queda do apoio popular e oportunismo em cenários de retomada de popularidade.
	Além desta introdução, o presente artigo possui uma seção que visa a discutir, brevemente, a dinâmica política do enfrentamento da crise. Em seguida, há uma apresentação das hipóteses, a discussão metodológica e dos resultados. 

# O que há em jogo com a pandemia? 
  
A pandemia, atrelada a já existente discussão acerca da crise da democracia (KEANE, 2020), traz importantes desafios de confiança, culpabilidade e entendimento (FLINDERS, 2020). Existem debates acerca da capacidade democrática em responder a atual crise de saúde pública (KAVANAGH; SINGH, 2020), demonstrando que em comparação com regimes autoritários as democracias responderam pior ao começo da pandemia (CEPALUNI; DORSCH; BRANYICZKI, 2020).
Tomando o enfoque sociopolítico, as medidas de distanciamento social trouxeram maior apoio a governos europeus, aumentando até mesmo o grau de satisfação com a democracia (BOL et al., 2020). Para o caso norte americano, pesquisadores apontam para o fato de que as crenças políticas podem afetar a percepção sobre os riscos existentes da pandemia (BARRIOS; HOCHBERG, 2020), dificultando, até mesmo, medidas de enfrentamento ao vírus (PAINTER; QIU, 2020). Já para o caso brasileiro, um estudo demonstra como o medo pode, inclusive, unir grupos ideologicamente afastados (PEREIRA; MEDEIROS; BERTHOLINI, 2020).
A pandemia gera enorme insegurança e instabilidade em seus momentos iniciais. As medidas de combate ao vírus baseiam-se no distanciamento social, com possíveis períodos de “lockdown”, o fechamento obrigatório de estabelecimentos públicos e a vedação de atividades que promovam aglomeração. As medidas de enfrentamento são importante termômetro para a opinião pública, possivelmente levando a maior ou menor adesão às práticas recomendadas, como higienização contínua das mãos, distanciamento social e o uso de máscaras. Gestores passam a ser responsabilizados por suas ações e, no Brasil, a disputa entre Governo Federal de um lado, e governos estaduais e municipais de outro acirrou o conflito político nacional, impossibilitando qualquer efeito de união em torno de uma causa comum – não houve uma dinâmica de “rally ‘round the flag”. Muito ao contrário: Bolsonaro, como fazem populistas, apostou no acirramento da polarização, defendendo posições controversas, muitas delas não apoiadas por evidências empíricas.
 	Do outro lado da moeda, países com muita desigualdade e pobres sofrem ainda mais, pois o distanciamento social é inviável para grande parte da população: os mais vulneráveis e pobres. Em estados federados, há a extrema pressão existente advinda da queda de arrecadação dos entes políticos e a recessão econômica potencial. 
Aqueles no comando do Poder Executivo têm que lidar com escolhas de distanciamento, que impactam o gasto público e a arrecadação de tributos, e de flexibilização/encerramento do distanciamento, que geram a diminuição dos impactos econômicos negativos e aumentam a probabilidade de mortes que inevitavelmente serão atribuídas a cargo de tal medida. Esse é o grande dilema posto acerca da pandemia na política nacional.
É plausível supor que o Poder Executivo sofra em maior escala , tendo como pressuposto o fato de ser linha de frente das medidas tomadas, a vitrine da gestão nacional, estadual e municipal e o principal afetado quando da recuperação econômica. Os eleitores julgarão os seus candidatos frente a um cenário de crise e que pode ser extremamente associado as ações daqueles no comando do Executivo. Já os parlamentares operam em um cenário de alto custo de entendimento e participação (NICOLAU, 2017) e possuem grande margem para evitar efeitos negativos. 
Como exemplo disso, a literatura aponta que a reeleição de presidentes é sensível à situação econômica (CAMPELLO; ZUCCO, 2016; KRAMER, 1971), sendo considerada, inclusive, fator de peso para interrupção de mandados (PÉREZ-LIÑÁN, 2007). No caso brasileiro, há evidência para a desvantagem existente nas reeleições para prefeito (KLAŠNJA; TITIUNIK, 2017). 
No entanto, com relação aos deputados federais, trabalhos demonstram a vantagem na reeleição existente para incumbentes (MEIRELES, 2019) e a falha dos eleitores em punir condutas ilegais (BOAS; HIDALGO; MELO, 2019) e a corrupção, mitigada pelo grau de financiamento de campanha (JUCÁ; MELO; RENNÓ, 2016).  
Dessa forma, pode se supor o baixo custo da crítica a medidas que flexibilizem o distanciamento e o elevado grau de retorno em posicionar-se a favor do distanciamento social, em detrimento da postura favorável da retomada econômica. Chefes do Executivo não podem se dar a esse luxo: estão impelidos a tomar decisões, de um lado ou de outro, levando em conta a opinião pública e as recomendações de especialistas. 
Isso, obviamente, não implica reduzir a postura parlamentar a créditos e prejuízos, dado que é legitimo supor a preocupação e a ação em direção à “boa política”. Reduzir as ações dos deputados e senadores ao mero diálogo entre aproveitar-se de efeitos positivos e esquivar-se de efeitos negativos, seria, no mínimo, simplista. No entanto, antes de fragilizar as preferências individuais e coletivas dos parlamentares, o argumento tem por base o pressuposto teórico de que políticos são avessos ao risco (WEAVER, 1986) e que se encontram em um constante cálculo de ações com benefícios concentrados e custos dispersos (ARNOLD, 1990).
O quão endógena a ideologia é a preferência pelo distanciamento social? Ponto relevante, tomando o caso brasileiro, dado a existência de um grande embate a nível federal e estadual, demonstrando posição antagônica entre governadores e o Presidente e forte jogo de transferência de responsabilidade (MELO, 2020). Estar a favor do distanciamento significaria estar do mesmo lado de governadores, organizações internacionais, diversos países, especialistas e da opinião pública e contra o Governo Federal, especialmente nos momentos iniciais da pandemia.
O distanciamento social, em si, apesar de ter implicação econômica e à saúde pública claras, não possui posicionamento ideológico evidente. No entanto, não é de todo equivocado apontar para o fato de que, em última instância, a questão se reduz a: “O quanto vale expor vidas para salvar a economia?”. A resposta para a essa questão parece apontar para o fato de que o medo da morte aproxima ideologias distintas (PEREIRA; MEDEIROS; BERTHOLINI, 2020).
Se o medo da morte aproxima ideologias, é possível dizer que o medo da morte aproxima partidos? Seria problemático supor que partidos de oposição poderiam em algum momento apoiar medidas favoráveis ao Governo Federal no contexto do enfrentamento da pandemia, especificamente no que diz respeito ao encerramento do distanciamento social, por mais que o seu interesse fosse em direção a ações eficazes de combate em diálogo com o Governo Federal. Esse é um claro caso no qual sistemas multipartidários premiam posicionamentos fortes por parte de partidos em detrimento de posturas omissas (WEAVER, 1986). 
Apoiar o distanciamento poderia ser entendido como importante ação da oposição ao Governo, não sendo surpreendente a sua constatação empírica. Não tão claro assim é se o engajamento em um conflito aberto varia de acordo com o a popularidade do Presidente. Mais especificamente: à medida que a popularidade do Presidente cresce, é possível observar o efeito previsto pela literatura de não confrontação (HETHERINGTON; NELSON, 2003)? 
Com relação àqueles próximos ao Presidente, resta se perguntar qual seria o incentivo a apoiá-lo, tendo como pressuposto o radicalismo das condutas contra o distanciamento, e o altíssimo custo de estar associado a elas. Por essa razão, seria plausível supor que os apoiadores do Presidente no parlamento escolhessem evitar a sua defesa, cuidar da pandemia em outros aspectos relevantes e com baixa exposição a temas polêmicos e impopulares. 
É de se imaginar, igualmente, que o apoio do Presidente tenha um custo, e que os recursos federais enviados para âmbito local possuam forte poder explicativo para o posicionamento individual e coletivo dos parlamentares (PEREIRA; MUELLER, 2002, 2003). No entanto, o presente trabalho utilizará como variável explicativa a popularidade do Presidente, tentando se aproximar a troca de recursos através dos partidos que compõem sua base de apoio – ideia operacionalizada pela ocupação de ministérios no gabinete. 
